import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import { useState } from "react";
import AboutComp from "../components/AboutComp";
import ServicesComp from "../components/ServicesComp";
import OurSoftware from "../components/OurSoftwareComp";
import ContactComp from "../components/ContactComp";
import Footer from "../components/Footer";
import { useRouter } from "next/router";
import Nav from "../components/Nav";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <div className="flex flex-col gap-10">
      <Head>
        <title>Software</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header></Header>
   <div className='hidden md:block' ><Nav></Nav></div>
      <AboutComp></AboutComp>
     <ServicesComp></ServicesComp>
  <OurSoftware></OurSoftware>
    {/* <div className={"text-4xl font-bold w-full bg-no-repeat h-[200px] bg-[url('/images/img-9.png')] mt-20 pt-16 pb-16" + inter.className}>How it works</div> */}

<ContactComp></ContactComp>


<Footer></Footer>
    </div>
  );
}
